#!/bin/sh

echo "Updating vim submodules"
git submodule init
git submodule update

# Install pip, if necessary
# This might be problematic on a non-Debian distro
if [ $(dpkg-query -W -f='${Status}' python-pip 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
    echo "pip doesn't appear to be here, installing..."
    sudo apt-get install python-pip
fi

# Install powerline
echo "Installing powerline-status"
sudo pip install powerline-status

