#!/bin/sh

## Needed to setup
# brew install python (will install python3)
# brew install vim --with-python3
# still broken?

echo "Updating vim submodules"
git submodule init
git submodule update

# Make symlinks
ln -s $PWD/.tmux.conf ~/.tmux.conf
ln -s $PWD/.vimrc ~/.vimrc
ln -s $PWD/.vim ~/.vim
ln -s $PWD/.bashrc ~/.bashrc
ln -s $PWD/.ideavimrc ~/.ideavimrc
ln -s $PWD/.git-completion.bash ~/.git-completion.bash


# Provide Vim a place to put swapfiles
mkdir ~/.swp

if [ $(command -v pip3 2>/dev/null | grep -c "pip3") -eq 0 ]; then
    echo "pip3 doesn't appear to be installed"
    echo "this is needed for some things"
    exit 1
fi

# Install tmux-powerline
git clone git@github.com:erikw/tmux-powerline.git

echo "Installing psutil"
pip3 install psutil

# Install TPM
echo "Installing tmux plugin manager"
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm




